# Настройки Kitty для macOS

shell /opt/homebrew/bin/fish
map super+n new_window /opt/homebrew/bin/fish

# Скрывает заголовок окна и учитывает вырез MacBook
hide_window_decorations titlebar-and-notch

macos_quit_when_last_window_closed yes
macos_titlebar_color background
macos_traditional_fullscreen no

# Option оставляем как Mac-символы (не Alt в терминале)
# macos_option_as_alt no
